---
abstract: 'XS functions to assist in parsing C<sub>-like syntax'
author:
  - 'Paul Evans <leonerd@leonerd.org.uk>'
build_requires:
  ExtUtils::CBuilder: '0'
  Sub::Util: '0'
  Test2::V0: '0'
configure_requires:
  Module::Build: '0.4004'
dynamic_config: 1
generated_by: 'Module::Build version 0.4234, CPAN::Meta::Converter version 2.150010'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: '1.4'
name: XS-Parse-Sublike
provides:
  Sublike::Extended:
    file: lib/Sublike/Extended.pm
    version: '0.23'
  XS::Parse::Sublike:
    file: lib/XS/Parse/Sublike.pm
    version: '0.23'
  XS::Parse::Sublike::Builder:
    file: lib/XS/Parse/Sublike/Builder.pm
    version: '0.23'
requires:
  File::ShareDir: '1.00'
  perl: '5.016'
resources:
  license: http://dev.perl.org/licenses/
version: '0.23'
x_serialization_backend: 'CPAN::Meta::YAML version 0.018'
