#!/bin/sh

cd $TDIR

# we need to compile stuff in t/
perl Build.PL
./Build
./Build test

# and now remove everything except t/
# before `smoke' is run
find . -maxdepth 1 -type f -delete
rm -r blib/ lib/ inc/ hax/ _build/
