#!/bin/sh

cd $TDIR

# we need to compile stuff in t/
perl Build.PL
./Build
# redirect STDERR to STDOUT, autopkgtest fails otherwise
./Build test 2>&1

# and now remove everything except t/
# before `smoke' is run
find . -maxdepth 1 -type f -delete
rm -r blib/ lib/ inc/ hax/ include/ share/ src/ _build/
